#' Parse DrugBank XML to DuckDB (long format, batch inserts)
#'
#' @param xml_file Path to full_database.xml
#' @param duckdb_file Path to output .duckdb file
#' @param batchsize Number of drugs to batch insert (default 1000)
#' @param overwrite Overwrite existing DuckDB file (default FALSE)
#' @export
drugbank_xml2rdb <- function(xml_file, duckdb_file,
                                    batchsize = 5000,
                                    overwrite = FALSE,
                                    log_every = 500,
                                    est_total_drugs = 200000) {

  if (file.exists(duckdb_file) && !overwrite) {
    message("DuckDB already exists.")
    return(invisible(NULL))
  }
  reticulate::py_discover_config()
  unlink(duckdb_file)

  reticulate::py_require(c("duckdb", "lxml"))

  py_code <- paste(c(
    "from lxml import etree as ET",
    "import duckdb",
    "import time",
    "def strip(tag):",
    "    return tag.split('}',1)[1] if '}' in tag else tag",
    paste0("xml_file = r'", xml_file, "'"),
    paste0("db_file = r'", duckdb_file, "'"),
    "con = duckdb.connect(db_file)",
    "# ---------------- SCHEMA ----------------",
    "con.execute('''",
    "CREATE TABLE drug (drug_id TEXT, name TEXT, type TEXT)''')",
    "con.execute('''",
    "CREATE TABLE drug_synonym (drug_id TEXT, synonym TEXT)''')",
    "con.execute('''",
    "CREATE TABLE drug_external_id (drug_id TEXT, resource TEXT, identifier TEXT)''')",
    "con.execute('''",
    "CREATE TABLE drug_atc (drug_id TEXT, atc_code TEXT, level1 TEXT, level2 TEXT, level3 TEXT, level4 TEXT, level5 TEXT)''')",
    paste0("BATCH = ", batchsize),
    paste0("LOG_EVERY = ", log_every),
    paste0("TOTAL_EST = ", est_total_drugs),
    "drug_rows = []",
    "syn_rows = []",
    "ext_rows = []",
    "atc_rows = []",
    "count = 0",
    "start_time = time.time()",
    "last_time = start_time",
    "last_count = 0",
    "# ---------------- STREAM PARSE ----------------",
    "context = ET.iterparse(xml_file, events=('end',), recover=True)",
    "for event, elem in context:",
    "    if strip(elem.tag) != 'drug':",
    "        continue",
    "    drug_id = None",
    "    name = None",
    "    dtype = elem.attrib.get('type')",
    "    for child in elem:",
    "        t = strip(child.tag)",
    "        if t == 'drugbank-id' and child.text:",
    "            drug_id = child.text",
    "        elif t == 'name' and child.text:",
    "            name = child.text",
    "    if not drug_id:",
    "        elem.clear()",
    "        continue",
    "    drug_rows.append((drug_id, name, dtype))",
    "    # ---------------- SYNONYMS ----------------",
    "    for child in elem:",
    "        if strip(child.tag) == 'synonyms':",
    "            for s in child:",
    "                if s.text:",
    "                    syn_rows.append((drug_id, s.text.lower()))",
    "    # ---------------- EXTERNAL IDS ----------------",
    "    for child in elem:",
    "        if strip(child.tag) == 'external-identifiers':",
    "            for ext in child:",
    "                r = None",
    "                i = None",
    "                for x in ext:",
    "                    t = strip(x.tag)",
    "                    if t == 'resource':",
    "                        r = x.text",
    "                    elif t == 'identifier':",
    "                        i = x.text",
    "                if r and i:",
    "                    ext_rows.append((drug_id, r, i))",
    "    # ---------------- ATC ----------------",
    "    for child in elem:",
    "        if strip(child.tag) == 'atc-codes':",
    "            for atc in child:",
    "                code = atc.attrib.get('code')",
    "                lvl = {'1':None,'2':None,'3':None,'4':None,'5':None}",
    "                for x in atc:",
    "                    if strip(x.tag) == 'level':",
    "                        c = x.attrib.get('code')",
    "                        t = x.text",
    "                        if not c: continue",
    "                        if len(c)==1: lvl['1']=t",
    "                        elif len(c)==3: lvl['2']=t",
    "                        elif len(c)==4: lvl['3']=t",
    "                        elif len(c)==5: lvl['4']=t",
    "                        elif len(c)==7: lvl['5']=t",
    "                atc_rows.append((drug_id, code, lvl['1'], lvl['2'], lvl['3'], lvl['4'], lvl['5']))",
    "    count += 1",
    "    # ---------------- PROGRESS LOG ----------------",
    "    if count % LOG_EVERY == 0:",
    "        now = time.time()",
    "        elapsed = now - start_time",
    "        speed = count / elapsed if elapsed > 0 else 0",
    "        eta = (TOTAL_EST - count) / speed if speed > 0 else 0",
    "        print(f'[DrugBank] {count:,} drugs | {speed:.2f}/sec | elapsed {elapsed/60:.1f} min | ETA {eta/60:.1f} min', flush=True)",
    "        last_time = now",
    "        last_count = count",
    "    # ---------------- BATCH FLUSH ----------------",
    "    if count % BATCH == 0:",
    "        print(f'[Flush] {count:,} drugs → writing batch', flush=True)",
    "        if drug_rows:",
    "            con.executemany('INSERT INTO drug VALUES (?, ?, ?)', drug_rows)",
    "            drug_rows = []",
    "        if syn_rows:",
    "            con.executemany('INSERT INTO drug_synonym VALUES (?, ?)', syn_rows)",
    "            syn_rows = []",
    "        if ext_rows:",
    "            con.executemany('INSERT INTO drug_external_id VALUES (?, ?, ?)', ext_rows)",
    "            ext_rows = []",
    "        if atc_rows:",
    "            con.executemany('INSERT INTO drug_atc VALUES (?, ?, ?, ?, ?, ?, ?)', atc_rows)",
    "            atc_rows = []",
    "    elem.clear()",
    "# ---------------- FINAL FLUSH ----------------",
    "if drug_rows:",
    "    con.executemany('INSERT INTO drug VALUES (?, ?, ?)', drug_rows)",
    "if syn_rows:",
    "    con.executemany('INSERT INTO drug_synonym VALUES (?, ?)', syn_rows)",
    "if ext_rows:",
    "    con.executemany('INSERT INTO drug_external_id VALUES (?, ?, ?)', ext_rows)",
    "if atc_rows:",
    "    con.executemany('INSERT INTO drug_atc VALUES (?, ?, ?, ?, ?, ?, ?)', atc_rows)",
    "con.close()",
    "print('DONE:', count)"
  ), collapse = "\n")

  reticulate::py_run_string(py_code)

  message("DrugBank RDB built successfully.")
}
